apiVersion: v1
# K8 in Docker : Secret (Sensitive configurations)
kind: Secret
metadata:
  name: postgres-secret
# The type Opaque is default in K8 (non - transparent encoding)
# This password is in plain text here purely for learning purposes. In a real environment this value would come from a secrets manager or vault, never typed directly into a file that gets committed to source control.

type: Opaque
stringData:
  # DB Password (pass in Base64 in UI but we can still read in YAML if we want)
  DB_PASSWORD: "12345"
