apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  # At a time, only a single node can read and write
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
