--Book Categories Tab;e
CREATE TABLE public."BookCategories" (
	"CategoryId" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"CategoryName" text NOT NULL,
	CONSTRAINT "PK_BookCategories" PRIMARY KEY ("CategoryId")
);

--Books Table
CREATE TABLE public."Books" (
	"BookId" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Title" text NOT NULL,
	"Author" text NOT NULL,
	"ISBN" text NOT NULL,
	"CategoryId" int4 NOT NULL,
	CONSTRAINT "PK_Books" PRIMARY KEY ("BookId"),
	CONSTRAINT "FK_Books_BookCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."BookCategories"("CategoryId") ON DELETE CASCADE
);

--Book Copies Table
CREATE TABLE public."BookCopies" (
	"CopyId" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"BookId" int4 NOT NULL,
	"CopyCode" text NOT NULL,
	"Status" int4 NOT NULL,
	CONSTRAINT "PK_BookCopies" PRIMARY KEY ("CopyId"),
	CONSTRAINT "FK_BookCopies_Books_BookId" FOREIGN KEY ("BookId") REFERENCES public."Books"("BookId") ON DELETE CASCADE
);

--Members Table
CREATE TABLE public."Members" (
	"MemberId" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Name" text NOT NULL,
	"Email" text NOT NULL,
	"MembershipType" int4 NOT NULL,
	"IsActive" bool NOT NULL,
	"JoinedAt" timestamptz NOT NULL,
	"Password" text DEFAULT ''::text NOT NULL,
	"Role" int4 DEFAULT 0 NOT NULL,
	CONSTRAINT "PK_Members" PRIMARY KEY ("MemberId")
);

--Damage Log Table
CREATE TABLE public."DamageLogs" (
	"DamageId" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"MemberId" int4 NOT NULL,
	"CopyId" int4 NOT NULL,
	"Description" text NOT NULL,
	"DateOfEntry" date NOT NULL,
	status int4 DEFAULT 0 NOT NULL,
	CONSTRAINT "PK_DamageLogs" PRIMARY KEY ("DamageId"),
	CONSTRAINT "FK_DamageLogs_BookCopies_CopyId" FOREIGN KEY ("CopyId") REFERENCES public."BookCopies"("CopyId") ON DELETE CASCADE,
	CONSTRAINT "FK_DamageLogs_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES public."Members"("MemberId") ON DELETE CASCADE
);

--Fine Table:
CREATE TABLE public."Fines" (
	"FineId" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"BorrowingId" int4 NOT NULL,
	"MemberId" int4 NOT NULL,
	"Amount" numeric NOT NULL,
	"IsPaid" bool NOT NULL,
	"PaidAt" timestamptz NULL,
	CONSTRAINT "PK_Fines" PRIMARY KEY ("FineId"),
	CONSTRAINT "FK_Fines_Borrowings_BorrowingId" FOREIGN KEY ("BorrowingId") REFERENCES public."Borrowings"("BorrowingId") ON DELETE CASCADE,
	CONSTRAINT "FK_Fines_Members_MemberId" FOREIGN KEY ("MemberId") REFERENCES public."Members"("MemberId") ON DELETE CASCADE
);

--Code First Approach was followed
--Default data imported using seed.sql in DAL
