# virtual web server
# configurations of SPA to be run using this server
server {    
    # nginx port
    listen 80;
    # storage location of frontend files
    root /usr/share/nginx/html;
    # if directory instead of files, serve default (index.html)
    index index.html;

    # SPA routing + forward API to backend
    # defines rules of routing for every frontend url
    # $uri(part1) $uri/ (part2) /index.html(part3);
    # URI = url, URI / = directory, /index.html = default file (if url does not exists)
    #part 1 => If URI present, return it. part2 => if it exisits as dir return. part 3 => else return the default index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
